services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn alma.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - db_volume:/app/db
    expose:
      - 8000
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8080:8080"
    depends_on:
      - django

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
  db_volume:
