version: "3.2"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - django_static:/app/static
      - django_media:/app/media
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    command: npm run dev
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - django_static:/app/static
      - django_media:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    # depends_on:
    #   - backend
    #   - frontend

volumes:
  django_static:
  django_media:
